### ISSUE TITLE
IllegalMonitorStateException thrown from MslControl.deleteMasterToken()

### ISSUE THREAD

**Issue by wmiaw** [Netflix/msl#200]
This is intermittently getting thrown by the example simple MSL server. It's not clear how to get the server into this bad state. Maybe sending a request from the example simple MSL client with a master token that the server didn't already know about?

 ```
Caused by: com.netflix.msl.MslInternalException: Error sending the response.
        at com.netflix.msl.msg.MslControl$RespondService.call(MslControl.java:2896)
        at com.netflix.msl.msg.MslControl$RespondService.call(MslControl.java:2533)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.netflix.msl.msg.MslControl$SynchronousExecutor.execute(MslControl.java:277)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
        at com.netflix.msl.msg.MslControl.respond(MslControl.java:3640)
        at server.SimpleServlet.doPost(SimpleServlet.java:219)
        ... 24 more
Caused by: java.lang.IllegalMonitorStateException: attempt to unlock read lock, not locked by current thread
        at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.unmatchedUnlockException(ReentrantReadWriteLock.java:444)
        at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryReleaseShared(ReentrantReadWriteLock.java:428)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.releaseShared(AbstractQueuedSynchronizer.java:1341)
        at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.unlock(ReentrantReadWriteLock.java:881)
        at com.netflix.msl.msg.MslControl.deleteMasterToken(MslControl.java:936)
        at com.netflix.msl.msg.MslControl.updateCryptoContexts(MslControl.java:996)
        at com.netflix.msl.msg.MslControl.send(MslControl.java:1605)
        at com.netflix.msl.msg.MslControl.access$900(MslControl.java:189)
        at com.netflix.msl.msg.MslControl$RespondService.trustedNetworkExecute(MslControl.java:2641)
        at com.netflix.msl.msg.MslControl$RespondService.call(MslControl.java:2832)
```

**Comment by wmiaw** [comment]
Cannot reproduce.
